MASGlobalTest.UI/Controllers/EmployeeController.cs
using MASGlobalTest.BL.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MASGlobalTest.UI.Controllers
{
    public class EmployeeController : ApiController
    {
        // GET: api/Employee
        public IEnumerable<Employee> Get()
        {
            try
            {
                return Employee.GetEmployees();
            }
            catch (Exception ex)
            {
                BadRequest(ex.Message);
                return null;
            }
        }

        // GET: api/Employee/5
        public Employee Get(int id)
        {
            try
            {
                return Employee.GetEmployeeByID(id);
            }
            catch (Exception ex)
            {
                BadRequest(ex.Message);
                return null;
            }
        }


    }
}

MASGlobalTest.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MASGlobalTest.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MASGlobalTest.UI/Controllers/SalaryController.cs
using MASGlobalTest.BL.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MASGlobalTest.UI.Controllers
{
    public class SalaryController : Controller
    {
        // GET: Salary
        public ActionResult Index(string id)
        {
            EmployeeController employeeAPI = new EmployeeController();
            var employees = employeeAPI.Get();

            if (!string.IsNullOrEmpty(id))
            {
                int idEmployee;
                if (Int32.TryParse(id, out idEmployee))
                {
                    employees = employees.Where(x => x.Id == idEmployee).ToList();
                }
            }

            return View(employees);
        }

        // GET: Salary/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }


    }
}

MASGlobalTest.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MASGlobalTest.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MASGlobalTest.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MASGlobalTest.UI/Views/Index.cshtml
@model IEnumerable<MASGlobalTest.BL.DTO.Employee>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContractTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HourlySalary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MonthlySalary)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContractTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HourlySalary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MonthlySalary)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MASGlobalTest.UI/Views/Salary/Index.cshtml
@model IEnumerable<MASGlobalTest.BL.DTO.Employee>

@{
    ViewBag.Title = "Employees Salary";
}

<h2>Employees Salary</h2>

<p>
@using (Html.BeginForm("Index", "Salary", FormMethod.Get)){
	<div class="form-inline">
	@Html.TextBox("id", "", new { @class = "form-control" })
	<input type="submit" value="Get Employees" class="btn btn-success" />
	</div>
}
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContractTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HourlySalary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MonthlySalary)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContractTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HourlySalary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MonthlySalary)
        </td>
    </tr>
}

</table>

MASGlobalTest.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MAS Global Consulting Test", "Index", "Salary", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Joisman Jiménez for <b>MAS Global Consulting</b></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>